server:
  port: 8070
  tomcat:
    maxThreads: 0
    uriEncoding: UTF-8
    basedir: target/tomcat
  servlet:
    contextPath: /
    session:
      timeout: -1s
redis:
  open: on  # 是否开启redis缓存  true开启   false关闭
  database: 0
  host: 127.0.0.1
  port: 6379
  password:    # 密码（默认为空）
  timeout: 6000ms  # 连接超时时长（毫秒）
  jedis:
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
spring:
  activemq:
    broker-url: tcp://123.57.58.39:61616
    user: admin
    password: admin
    close-timeout: 15s   # 在考虑结束之前等待的时间
    in-memory: false      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: active.queue
    topic-name: active.topic.name.model
  #  packages:
  #    trust-all: true #不配置此项，会报错
  pool:
    enabled: true
    max-connections: 10   #连接池最大连接数
    idle-timeout: 30000   #空闲的连接过期时间，默认为30秒
#  rabbitmq:
#    host: 127.0.0.1
#    port: 15672
#    username: guest
#    password: guest
#    publisher-confirms: true
#    virtual-host: /
#    connection-timeout: 5
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.142.129:9300
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wxb.commontest.dao.mysql
